
spring:
  application:
    name: realmeet

  profiles:
    active: ${PROFILE_ACTIVE:dev} # padrão (pode mudar via variável de ambiente)

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
